apiVersion: v2
name: ndb-operator
version: 0.2.0
kubeVersion: ">= 1.19.0-0"
description: A Helm chart for deploying the Oracle MySQL NDB Cluster Operator
appVersion: "8.0.30-0.3.0"
keywords:
  - NDB Operator
  - MySQL Cluster
  - NDB
  - Ndbcluster
home: https://github.com/mysql/mysql-ndb-operator
maintainers:
  - name: Lakshmi Narayanan Sreethar
    email: lakshmi.narayanan.sreethar@oracle.com
  - name: Dinesh Surya Prakash
    email: dinesh.prakash@oracle.com
annotations:
  artifacthub.io/images: |
    - name: ndb-operator
      image: mysql/ndb-operator:latest
  artifacthub.io/crds: |
    - kind: NdbCluster
      version: v1alpha1
      name: ndbcluster.mysql.oracle.com
      displayName: MySQL NDB Cluster
      description: MySQL NDB Cluster configuration
  artifacthub.io/crdsExamples: |
    - apiVersion: mysql.oracle.com/v1alpha1
      kind: NdbCluster
      metadata:
        name: my-ndb
      spec:
        nodeCount: 2
        redundancyLevel: 2
        mysqld:
          nodeCount: 2
  artifacthub.io/license: UPL-1.0
  artifacthub.io/prerelease: "true"
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Seamless Upgrades
