# Yaml file with default values for the NDB Operator templates

# default image, pull secret and pull policy
image: mydocker.mysql.oraclecorp.com/qa/ndb-operator:8.0.29-0.2.0
imagePullPolicy: IfNotPresent
imagePullSecretName:

# The operator is by default cluster-scoped.
# If this value is set to false, the operator will be namespace-scoped and
# will be watching for NdbCluster resource changes only in the namespace
# it is released into (controlled by helm's --namespace option).
clusterScoped: true
