# Create the secret with the password to be used for the root account
apiVersion: v1
kind: Secret
metadata:
  name: ndbop-mysql-secret
# Can use kubernetes.io/basic-auth type secret as well
type: Opaque
stringData:
  # password key is mandatory.
  # Everything else is ignored by the operator
  password: ndbpass
---
# MySQL Cluster with custom password for the root account
apiVersion: mysql.oracle.com/v1
kind: NdbCluster
metadata:
  name: example-ndb
spec:
  redundancyLevel: 2
  dataNode:
    nodeCount: 2
  mysqlNode:
    nodeCount: 2
    rootPasswordSecretName: ndbop-mysql-secret
