# ClusterRoles for the WebHook Server to access the non cluster-scoped resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ndb-operator-webhook-cr
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
# ClusterRoles for the WebHook Server to access the cluster-scoped resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ndb-operator-webhook-vwc-cr
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - list
      - patch
---
# Cluster roles for Ndb Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ndb-operator-cr
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
      - list
      - update
      - watch

  - apiGroups: [""]
    resources: ["services"]
    verbs:
      - get
      - list
      - update
      - create
      - watch

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs:
      - get
      - list
      - create
      - patch
      - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
      - create
      - delete

  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs:
      - create
      - patch

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
      - create
      - list
      - watch

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs:
      - create
      - get
      - list
      - patch
      - watch
      - delete

  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs:
      - create
      - get
      - list
      - watch

  - apiGroups: ["mysql.oracle.com"]
    resources:
      - ndbclusters
      - ndbclusters/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
