# Service to expose the webhook
apiVersion: v1
kind: Service
metadata:
  name: {{template "webhook-service.name" .}}
  namespace: {{.Release.Namespace}}
spec:
  ports:
    - port: {{template "webhook-service.port"}}
  selector:
    {{template "webhook-service.pod-label"}}
---
# This service is created to get an FQDN for operator pod.
# The FQDN of this service will be used as the host name
# when creating 'ndb-operator-user' user. Operator
# will use this user account to create/modify/delete the root
# user account.
apiVersion: v1
kind: Service
metadata:
  name: ndb-operator-svc
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: ndb-operator
  clusterIP: None
---
