# Service account for webhook server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-webhook-sa
  namespace: {{.Release.Namespace}}
---
# Service Account for Ndb Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-app-sa
  namespace: {{.Release.Namespace}}
