# source https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: ClusterIP
---
# Persistent volume claim to persist website data files
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress:5.6-php7.4
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              # To connect to mysqld service created by ndb-operator, use
              # WORDPRESS_DB_HOST as <cluster-name>-mysqld
              value: wordpress-ndb-mysqld
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Same as 'rootPasswordSecretName' defined for 'mysqld' ndb resource
                  name: wordpress-mysql-secret
                  key: password
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
